### ISSUE TITLE
想问一下楼主这个出错是什么问题

### ISSUE THREAD

**Issue by fjw1049** [Z-yq/TensorflowASR#37]
Traceback (most recent call last):
  File "run-test.py", line 82, in <module>
    asr = ASR(am_config, lm_config,punc_config)
  File "run-test.py", line 12, in __init__
    self.lm = LM(lm_config,punc_config)
  File "/home/w/ASR/LMmodel/trm_lm.py", line 16, in __init__
    self.am_featurizer = TextFeaturizer(config['am_token'])
  File "/home/w/ASR/utils/text_featurizers.py", line 78, in __init__
    self.stop = self.endid()
  File "/home/w/ASR/utils/text_featurizers.py", line 90, in endid
    return self.token_to_index['</S>']
KeyError: '</S>'

**Comment by ChristopheZhao** [comment]
这个地方代码对应的是将end_token转为id,你自己定义的词表里没有加入' \</S\> '?
